# Generated by Django 4.1.6 on 2023-02-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.FileField(null=True, upload_to=None, verbose_name='Resim'),
        ),
    ]
