# Generated by Django 4.1.6 on 2023-02-27 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0003_card_brand_card_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Yorumcu')),
                ('title', models.CharField(max_length=50, verbose_name='Yorum Başlığı')),
                ('text', models.TextField(max_length=500, verbose_name='Yorum')),
                ('date_now', models.DateTimeField(verbose_name='Yorum Yapılma Zamanı')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.card', verbose_name='Card')),
            ],
        ),
    ]
